# Generated by Django 5.0.1 on 2024-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostGresEmpl',
            fields=[
                ('recno', models.AutoField(primary_key=True, serialize=False)),
                ('empno', models.CharField(blank=True, max_length=16, null=True)),
                ('empname', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'empl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=1, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThaiEmpl',
            fields=[
                ('recno', models.AutoField(primary_key=True, serialize=False)),
                ('empno', models.CharField(blank=True, db_column='EMPNO', max_length=16, null=True)),
                ('empname', models.CharField(blank=True, db_column='EMPNAME', max_length=80, null=True)),
            ],
            options={
                'db_table': 'empl',
                'managed': False,
            },
        ),
    ]
