# Generated by Django 5.0.1 on 2024-03-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tbstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThaiEmpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recno', models.IntegerField(db_column='RECNO')),
                ('empno', models.CharField(blank=True, db_column='EMPNO', max_length=16, null=True)),
                ('empname', models.CharField(blank=True, db_column='EMPNAME', max_length=80, null=True)),
            ],
            options={
                'db_table': 'empl',
                'managed': False,
            },
        ),
    ]
